// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package de.uvwxy.whereami2.proto;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required double latitude = 1;
    /**
     * <code>required double latitude = 1;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required double latitude = 1;</code>
     */
    double getLatitude();

    // required double longitude = 2;
    /**
     * <code>required double longitude = 2;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 2;</code>
     */
    double getLongitude();

    // required double altitude = 3;
    /**
     * <code>required double altitude = 3;</code>
     */
    boolean hasAltitude();
    /**
     * <code>required double altitude = 3;</code>
     */
    double getAltitude();

    // required double bearing = 4;
    /**
     * <code>required double bearing = 4;</code>
     */
    boolean hasBearing();
    /**
     * <code>required double bearing = 4;</code>
     */
    double getBearing();

    // required double accuracy = 5;
    /**
     * <code>required double accuracy = 5;</code>
     */
    boolean hasAccuracy();
    /**
     * <code>required double accuracy = 5;</code>
     */
    double getAccuracy();

    // required string provider = 6;
    /**
     * <code>required string provider = 6;</code>
     */
    boolean hasProvider();
    /**
     * <code>required string provider = 6;</code>
     */
    java.lang.String getProvider();
    /**
     * <code>required string provider = 6;</code>
     */
    com.google.protobuf.ByteString
        getProviderBytes();

    // required double speed = 7;
    /**
     * <code>required double speed = 7;</code>
     */
    boolean hasSpeed();
    /**
     * <code>required double speed = 7;</code>
     */
    double getSpeed();

    // required int64 time = 8;
    /**
     * <code>required int64 time = 8;</code>
     */
    boolean hasTime();
    /**
     * <code>required int64 time = 8;</code>
     */
    long getTime();

    // required double name = 1000;
    /**
     * <code>required double name = 1000;</code>
     */
    boolean hasName();
    /**
     * <code>required double name = 1000;</code>
     */
    double getName();
  }
  /**
   * Protobuf type {@code de.uvwxy.whereami2.proto.Location}
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessage
      implements LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Location(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }

    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              latitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              longitude_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              altitude_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              bearing_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              accuracy_ = input.readDouble();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              provider_ = input.readBytes();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              speed_ = input.readDouble();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              time_ = input.readInt64();
              break;
            }
            case 8001: {
              bitField0_ |= 0x00000100;
              name_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uvwxy.whereami2.proto.Messages.internal_static_de_uvwxy_whereami2_proto_Location_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uvwxy.whereami2.proto.Messages.internal_static_de_uvwxy_whereami2_proto_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.uvwxy.whereami2.proto.Messages.Location.class, de.uvwxy.whereami2.proto.Messages.Location.Builder.class);
    }

    public static com.google.protobuf.Parser<Location> PARSER =
        new com.google.protobuf.AbstractParser<Location>() {
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Location(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required double latitude = 1;
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>required double latitude = 1;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double latitude = 1;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    // required double longitude = 2;
    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>required double longitude = 2;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double longitude = 2;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    // required double altitude = 3;
    public static final int ALTITUDE_FIELD_NUMBER = 3;
    private double altitude_;
    /**
     * <code>required double altitude = 3;</code>
     */
    public boolean hasAltitude() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double altitude = 3;</code>
     */
    public double getAltitude() {
      return altitude_;
    }

    // required double bearing = 4;
    public static final int BEARING_FIELD_NUMBER = 4;
    private double bearing_;
    /**
     * <code>required double bearing = 4;</code>
     */
    public boolean hasBearing() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double bearing = 4;</code>
     */
    public double getBearing() {
      return bearing_;
    }

    // required double accuracy = 5;
    public static final int ACCURACY_FIELD_NUMBER = 5;
    private double accuracy_;
    /**
     * <code>required double accuracy = 5;</code>
     */
    public boolean hasAccuracy() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required double accuracy = 5;</code>
     */
    public double getAccuracy() {
      return accuracy_;
    }

    // required string provider = 6;
    public static final int PROVIDER_FIELD_NUMBER = 6;
    private java.lang.Object provider_;
    /**
     * <code>required string provider = 6;</code>
     */
    public boolean hasProvider() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string provider = 6;</code>
     */
    public java.lang.String getProvider() {
      java.lang.Object ref = provider_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          provider_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string provider = 6;</code>
     */
    public com.google.protobuf.ByteString
        getProviderBytes() {
      java.lang.Object ref = provider_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        provider_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required double speed = 7;
    public static final int SPEED_FIELD_NUMBER = 7;
    private double speed_;
    /**
     * <code>required double speed = 7;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required double speed = 7;</code>
     */
    public double getSpeed() {
      return speed_;
    }

    // required int64 time = 8;
    public static final int TIME_FIELD_NUMBER = 8;
    private long time_;
    /**
     * <code>required int64 time = 8;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int64 time = 8;</code>
     */
    public long getTime() {
      return time_;
    }

    // required double name = 1000;
    public static final int NAME_FIELD_NUMBER = 1000;
    private double name_;
    /**
     * <code>required double name = 1000;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required double name = 1000;</code>
     */
    public double getName() {
      return name_;
    }

    private void initFields() {
      latitude_ = 0D;
      longitude_ = 0D;
      altitude_ = 0D;
      bearing_ = 0D;
      accuracy_ = 0D;
      provider_ = "";
      speed_ = 0D;
      time_ = 0L;
      name_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAltitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBearing()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccuracy()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProvider()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, altitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, bearing_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, accuracy_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getProviderBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, speed_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, time_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeDouble(1000, name_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, altitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, bearing_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, accuracy_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getProviderBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, speed_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, time_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1000, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.uvwxy.whereami2.proto.Messages.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.uvwxy.whereami2.proto.Messages.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.uvwxy.whereami2.proto.Messages.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.uvwxy.whereami2.proto.Messages.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.uvwxy.whereami2.proto.Messages.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.uvwxy.whereami2.proto.Messages.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.uvwxy.whereami2.proto.Messages.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.uvwxy.whereami2.proto.Messages.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.uvwxy.whereami2.proto.Messages.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.uvwxy.whereami2.proto.Messages.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uvwxy.whereami2.proto.Messages.Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code de.uvwxy.whereami2.proto.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.uvwxy.whereami2.proto.Messages.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uvwxy.whereami2.proto.Messages.internal_static_de_uvwxy_whereami2_proto_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uvwxy.whereami2.proto.Messages.internal_static_de_uvwxy_whereami2_proto_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.uvwxy.whereami2.proto.Messages.Location.class, de.uvwxy.whereami2.proto.Messages.Location.Builder.class);
      }

      // Construct using de.uvwxy.whereami2.proto.Messages.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        altitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        bearing_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        accuracy_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        provider_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        speed_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        name_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uvwxy.whereami2.proto.Messages.internal_static_de_uvwxy_whereami2_proto_Location_descriptor;
      }

      public de.uvwxy.whereami2.proto.Messages.Location getDefaultInstanceForType() {
        return de.uvwxy.whereami2.proto.Messages.Location.getDefaultInstance();
      }

      public de.uvwxy.whereami2.proto.Messages.Location build() {
        de.uvwxy.whereami2.proto.Messages.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.uvwxy.whereami2.proto.Messages.Location buildPartial() {
        de.uvwxy.whereami2.proto.Messages.Location result = new de.uvwxy.whereami2.proto.Messages.Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.altitude_ = altitude_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bearing_ = bearing_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.accuracy_ = accuracy_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.provider_ = provider_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uvwxy.whereami2.proto.Messages.Location) {
          return mergeFrom((de.uvwxy.whereami2.proto.Messages.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.uvwxy.whereami2.proto.Messages.Location other) {
        if (other == de.uvwxy.whereami2.proto.Messages.Location.getDefaultInstance()) return this;
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasAltitude()) {
          setAltitude(other.getAltitude());
        }
        if (other.hasBearing()) {
          setBearing(other.getBearing());
        }
        if (other.hasAccuracy()) {
          setAccuracy(other.getAccuracy());
        }
        if (other.hasProvider()) {
          bitField0_ |= 0x00000020;
          provider_ = other.provider_;
          onChanged();
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLatitude()) {
          
          return false;
        }
        if (!hasLongitude()) {
          
          return false;
        }
        if (!hasAltitude()) {
          
          return false;
        }
        if (!hasBearing()) {
          
          return false;
        }
        if (!hasAccuracy()) {
          
          return false;
        }
        if (!hasProvider()) {
          
          return false;
        }
        if (!hasSpeed()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.uvwxy.whereami2.proto.Messages.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.uvwxy.whereami2.proto.Messages.Location) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required double latitude = 1;
      private double latitude_ ;
      /**
       * <code>required double latitude = 1;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000001;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      // required double longitude = 2;
      private double longitude_ ;
      /**
       * <code>required double longitude = 2;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000002;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      // required double altitude = 3;
      private double altitude_ ;
      /**
       * <code>required double altitude = 3;</code>
       */
      public boolean hasAltitude() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double altitude = 3;</code>
       */
      public double getAltitude() {
        return altitude_;
      }
      /**
       * <code>required double altitude = 3;</code>
       */
      public Builder setAltitude(double value) {
        bitField0_ |= 0x00000004;
        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double altitude = 3;</code>
       */
      public Builder clearAltitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        altitude_ = 0D;
        onChanged();
        return this;
      }

      // required double bearing = 4;
      private double bearing_ ;
      /**
       * <code>required double bearing = 4;</code>
       */
      public boolean hasBearing() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double bearing = 4;</code>
       */
      public double getBearing() {
        return bearing_;
      }
      /**
       * <code>required double bearing = 4;</code>
       */
      public Builder setBearing(double value) {
        bitField0_ |= 0x00000008;
        bearing_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double bearing = 4;</code>
       */
      public Builder clearBearing() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bearing_ = 0D;
        onChanged();
        return this;
      }

      // required double accuracy = 5;
      private double accuracy_ ;
      /**
       * <code>required double accuracy = 5;</code>
       */
      public boolean hasAccuracy() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required double accuracy = 5;</code>
       */
      public double getAccuracy() {
        return accuracy_;
      }
      /**
       * <code>required double accuracy = 5;</code>
       */
      public Builder setAccuracy(double value) {
        bitField0_ |= 0x00000010;
        accuracy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double accuracy = 5;</code>
       */
      public Builder clearAccuracy() {
        bitField0_ = (bitField0_ & ~0x00000010);
        accuracy_ = 0D;
        onChanged();
        return this;
      }

      // required string provider = 6;
      private java.lang.Object provider_ = "";
      /**
       * <code>required string provider = 6;</code>
       */
      public boolean hasProvider() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string provider = 6;</code>
       */
      public java.lang.String getProvider() {
        java.lang.Object ref = provider_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          provider_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string provider = 6;</code>
       */
      public com.google.protobuf.ByteString
          getProviderBytes() {
        java.lang.Object ref = provider_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          provider_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string provider = 6;</code>
       */
      public Builder setProvider(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        provider_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string provider = 6;</code>
       */
      public Builder clearProvider() {
        bitField0_ = (bitField0_ & ~0x00000020);
        provider_ = getDefaultInstance().getProvider();
        onChanged();
        return this;
      }
      /**
       * <code>required string provider = 6;</code>
       */
      public Builder setProviderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        provider_ = value;
        onChanged();
        return this;
      }

      // required double speed = 7;
      private double speed_ ;
      /**
       * <code>required double speed = 7;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required double speed = 7;</code>
       */
      public double getSpeed() {
        return speed_;
      }
      /**
       * <code>required double speed = 7;</code>
       */
      public Builder setSpeed(double value) {
        bitField0_ |= 0x00000040;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double speed = 7;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000040);
        speed_ = 0D;
        onChanged();
        return this;
      }

      // required int64 time = 8;
      private long time_ ;
      /**
       * <code>required int64 time = 8;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int64 time = 8;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>required int64 time = 8;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000080;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 time = 8;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        time_ = 0L;
        onChanged();
        return this;
      }

      // required double name = 1000;
      private double name_ ;
      /**
       * <code>required double name = 1000;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required double name = 1000;</code>
       */
      public double getName() {
        return name_;
      }
      /**
       * <code>required double name = 1000;</code>
       */
      public Builder setName(double value) {
        bitField0_ |= 0x00000100;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double name = 1000;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000100);
        name_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:de.uvwxy.whereami2.proto.Location)
    }

    static {
      defaultInstance = new Location(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:de.uvwxy.whereami2.proto.Location)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uvwxy_whereami2_proto_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uvwxy_whereami2_proto_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\030de.uvwxy.whereami2.pro" +
      "to\"\242\001\n\010Location\022\020\n\010latitude\030\001 \002(\001\022\021\n\tlon" +
      "gitude\030\002 \002(\001\022\020\n\010altitude\030\003 \002(\001\022\017\n\007bearin" +
      "g\030\004 \002(\001\022\020\n\010accuracy\030\005 \002(\001\022\020\n\010provider\030\006 " +
      "\002(\t\022\r\n\005speed\030\007 \002(\001\022\014\n\004time\030\010 \002(\003\022\r\n\004name" +
      "\030\350\007 \002(\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_de_uvwxy_whereami2_proto_Location_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_de_uvwxy_whereami2_proto_Location_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uvwxy_whereami2_proto_Location_descriptor,
              new java.lang.String[] { "Latitude", "Longitude", "Altitude", "Bearing", "Accuracy", "Provider", "Speed", "Time", "Name", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
